### ISSUE TITLE
Issue with libxml-ruby 2.7.0 and 2.8.0 on Cray XC30s

### ISSUE THREAD

**Issue by jjmetz** [christopherwharrop/rocoto#11]
There is an issue with libxml-2.8.0 (reproducible for me in 2.7.0) on a Cray XC30 when compiled with both icc and gcc and using ruby 1.8.7. It gives an undefined symbol error in libxml_ruby.so for xmlBufContent when certain relatively random modifications are made to the workflow file. These include having a large number (more than six or so) values for a metatask variable, adding a maxtries attribute for a metatask task, and adding an age attribute to a datadep.

I eventually resolved this error by checking out the latest version of libxml-ruby (version 3.0.0) and building with that instead, so it appears that they have fixed it in the latest versions.

**Comment by christopherwharrop** [comment]
Thank you for reporting this.  The libxml2 and libxml-ruby have a history of memory management issues.  Unfortunately, there isn't a viable alternative XML parser since the others are extremely slow.  Your timing is fantastic, btw!  I am getting ready to release Rocoto 1.2.4 (some bug fixes, plus support for PBSPro).  I will upgrade the libxml-ruby (the latest libxml2 is already being used) and test.  If it looks good, it will be included in 1.2.4 which I expect to be released in the next week or two.  Thank you again for taking the time to dig into this, I know how irritating those memory bugs can be.  It is much appreciated.

**Comment by christopherwharrop** [comment]
Initial testing looks good.  I have committed an upgrade to libxml-ruby 3.0.0 onto the master branch.  I am almost ready to tag the first release candidate for 1.2.4.  Assuming no problems are detected (I don't expect any) this will be included in 1.2.4 in the next week or two.

**Comment by christopherwharrop** [comment]
The libxml-ruby has been upgraded to 3.0.0.  Version 1.2.4-RC1 has been released and contains this update.  An official release is expected within one week.
