### ISSUE TITLE
Heterogeneous job card for Slurm

### ISSUE THREAD

**Issue by jkuang-exploro** [christopherwharrop/rocoto#71]
Current release of rocoto (1.3.1) does not support job card with non-uniform (heterogeneous) node map (3:38+2:39). This makes it challenging for some tasks that are sensitive to node count.

Example: Currently Rocoto will convert '12:ppn=19+2:ppn=18' to '14:ppn=19' automatically. It provides some sort of resilience(a good thing), but will break some jobs.

The ability to be able to submit job card with '12:ppn=19+2:ppn=18' is much appreciated.

**Comment by christopherwharrop-noaa** [comment]
The issue you are referring to is specific to Slurm.  The problem is that use of Slurm's heterogeneous job feature causes many other problems that are related to job tracking (treats each component of a job as a separate job) and interferes with enforcement of local policies.  It is therefore intentionally not supported by NOAA RDHPCS.  If you want to use non-uniform requests, you can still do it, but you have to use the features of the srun command inside your script instead.  Rocoto converts your request into a uniform allocation that can accommodate the desired non-uniform layout inside it.  

You can specify a non-uniform layout in your job script using the -m option for srun as documented [here](https://slurm.schedmd.com/srun.html):

In addition NOAA RDHPCS has provided some tools to make this a bit easier.  Please see the documentation [here:](https://rdhpcs-common-docs.rdhpcs.noaa.gov/wiki/index.php/Running_and_Monitoring_Jobs_on_Jet_and_Theia_-_SLURM#Specifying_a_processor_layout_for_your_job_.28non-uniform_or_arbitray_layout_example.29)
